# COMMANDS:
# docker-compose -f docker/docker-compose.yaml --env-file .env up: start all the services defined in your compose.yaml file
# docker-compose -f docker/docker-compose.yaml --env-file .env down: stop and remove the running services
# docker-compose -f docker/docker-compose.yaml --env-file .env logs: monitor the output of your running containers and debug issues, viewing logs
# docker-compose -f docker/docker-compose.yaml --env-file .env ps: lists all the services along with their current status

# version: "3.8"

services:

  # App Service
  app:
    image: ${IMAGE_NAME}
    container_name: ${ENV}_app_container_${VERSION}

    command:
      - python
      - app.py

    ports:
      - "${INFERENCE_PORT}:${INFERENCE_PORT}"

    volumes:
      - ../${BUCKET_NAME}:/app/${BUCKET_NAME}
      - ../config:/app/config
    
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 30s
    #   timeout: 10s

  # Streamlit Web App Service
  web-app:
    image: ${IMAGE_NAME}
    container_name: ${ENV}_web_app_container_${VERSION}

    command:
      - streamlit
      - run
      - scripts/web_app/web_app.py
      - --server.port
      - ${WEBAPP_PORT}
      - --server.address
      - ${WEBAPP_HOST}

    ports:
      - "${WEBAPP_PORT}:${WEBAPP_PORT}"

    volumes:
      - ../${BUCKET_NAME}:/app/${BUCKET_NAME}
      - ../config:/app/config

  # # Dummy service
  # dummy-service:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       - ARG_KEY=${ARG_VALUE}

  #   image: ${USERNAME}/${REPO_NAME}:${ENV}-image-${VERSION} # latest
  #   container_name: ${ENV}_container_name_${VERSION}

  #   command: # Overwrite the CMD commands specified in the Dockerfile
  #     - python
  #     - app.py

  #   environment:
  #     - ENV_KEY=${ENV_VALUE}

  #   ports:
  #     - "8000:8000"

  #   volumes:
  #     # - ${HOST_PATH}:/app # Mount the project directory
  #     - ../${BUCKET_NAME}:/app/${BUCKET_NAME}
  #     - ../config:/app/config

  #   deploy:
  #     replicas: 3
  #     update_config:
  #       parallelism: 2
  #       delay: 10s
  #     resources:
  #       limits:
  #         cpus: "0.5"
  #         memory: "512M"

  #   depends_on:
  #     dependence-service:
  #       condition: service_completed_successfully

volumes:
  datasets:
    labels:
      environment: "development"