#!/bin/bash
# chmod +x ./scripts/bash/unset_env.sh
# source ./scripts/bash/unset_env.sh

unset ENV \
    DATA_STORAGE_ENV \
    MODEL_STORAGE_ENV \
    ETL_ENV \
    MODEL_BUILDING_ENV \
    APP_ENV \
    REGION_NAME \
    BUCKET_NAME \
    ETL_LAMBDA_FUNCTION_NAME \
    MODEL_BUILDING_STEP_FUNCTIONS_NAME \
    MODEL_BUILDING_STEP_FUNCTIONS_ARN \
    MODEL_BUILDING_STEP_FUNCTIONS_FILE_NAME \
    DOCKER_REPOSITORY_TYPE \
    DOCKER_REPOSITORY_NAME \
    ECR_REPOSITORY_URI \
    DOCKERHUB_USERNAME \
    KXY_API_KEY \
    GITHUB_PAT \
    DOCKERHUB_TOKEN \
    AZURE_DEVOPS_REPO_URL \
    AZURE_DEVOPS_USERNAME \
    AZURE_DEVOPS_PAT \
    INFERENCE_HOST \
    INFERENCE_PORT \
    WEBAPP_HOST \
    WEBAPP_PORT \
    RAW_DATASETS_PATH \
    PROCESSING_DATASETS_PATH \
    INFERENCE_PATH \
    TRANSFORMERS_PATH \
    MODELS_PATH \
    SCHEMAS_PATH \
    MOCK_PATH \
    SEED

# Set environment variables
set -o allexport
source .env
set +o allexport