# # # # #
# GENERAL PARAMETERS
# # # # #

# PROJECT PARAMETERS
PROJECT_PARAMS:
  PROJECT_NAME: ml-accelerator
  TARGET: species # target column
  TASK: classification 
  # regression, classification, forecasting

# ENVIRONMENT PARAMETERS
ENV_PARAMS:
  ENV: dev
  VERSION: 1.0.0
  REGION: sa-east-1
  BUCKET: iris-classification-dev
  DATA_STORAGE_ENV: filesystem
  # filesystem, S3
  MODEL_STORAGE_ENV: filesystem
  # filesystem, S3, mlflow
  COMPUTE_ENV: local
  # local, sagemaker

# # # # #
# DATA PROCESSING PARAMETERS
# # # # # 

# STORAGE PARAMETERS
STORAGE_PARAMS:
  DATASET_NAME: iris

  PATHS_PARAMS:
    TRAINING_PATH:
      - datasets
      - training
    INFERENCE_PATH:
      - datasets
      - inference
    MODELS_PATH:
      - models
  
  DATA_EXTENTION: csv
  # csv, parquet
  PARTITION_COLUMNS: null

# DATA CLEANING PARAMETERS
DATA_CLEANING_PARAMS:
  OUTLIER_Z_THRESHOLD: 3.0

# FEATURE ENGINEERING PARAMETERS
FEATURE_ENGINEERING_PARAMS: null

# DATA TRANSFORMING PARAMETERS
DATA_TRANSFORMING_PARAMS:
  ENCODE_TARGET: true
  SCALE_NUM_FEATURES: true
  ENCODE_CAT_FEATURES: true

# FEATURE SELECTION PARAMETERS
FEATURE_SELECTION_PARAMS:
  N_FEATURES: null

# # # # #
# MODELING PARAMETERS
# # # # #

# ML DATASETS PARAMETERS
ML_DATASETS_PARAMS:
  TRAIN_TEST_RATIO: 0.8

# CLASSIFICATION PARAMETERS
CLASSIFICATION_PARAMS:
  BALANCE_TRAIN: true
  BALANCE_METHOD: SMOTE
  # RandomOverSampler, RandomUnderSampler, SMOTE
  CLASS_WEIGHT:
    1: 1
    0: 1
    2: 1
  CUTOFF: 0.5

# REGRESSION PARAMETERS
REGRESSION_PARAMS: null

# FORECASTING PARAMETERS
FORECASTING_PARAMS: null

# HYPER PARAMETER TUNING PARAMETERS
HYPER_PARAMETER_TUNING_PARAMS:
  ALGORITHMS:
    - random_forest
    - lightgbm
    - xgboost

  SEARCH_SPACE:
    - algorithm: random_forest
      hyper_parameters:
      - parameter_name: n_estimators
        space:
          dist: quniform
          min: 15
          max: 400
      - parameter_name: max_depth
        space:
          dist: quniform
          min: 15
          max: 200
      - parameter_name: min_samples_split
        space:
          dist: quniform
          min: 5
          max: 200
      - parameter_name: max_features
        space:
          dist: choice
          choices: 
          - 1.0
          - sqrt
    - algorithm: lightgbm
      hyper_parameters:
      - parameter_name: objective
        space:
          dist: choice
          choices:
          - regression 
          - regression_l1 
          - huber 
          - quantile 
          - mape
      - parameter_name: boosting_type
        space:
          dist: choice
          choices:
          - gbdt 
          - dart
      - parameter_name: n_estimators
        space:
          dist: quniform
          min: 5
          max: 300
      - parameter_name: max_depth
        space:
          dist: quniform
          min: 1
          max: 150
      - parameter_name: min_child_samples
        space:
          dist: quniform
          min: 5
          max: 100
      - parameter_name: learning_rate
        space:
          dist: loguniform
          min: 0.001
          max: 0.3
      - parameter_name: num_leaves
        space:
          dist: quniform
          min: 5
          max: 150
      - parameter_name: colsample_bytree
        space:
          dist: uniform
          min: 0.6
          max: 1.0
    - algorithm: xgboost
      hyper_parameters:
      - parameter_name: objective
        space:
          dist: choice
          choices:
          - reg:squarederror
          - reg:absoluteerror
          - reg:quantileerror
      - parameter_name: booster
        space:
          dist: choice
          choices:
          - gbtree
          - dart
      - parameter_name: eta
        space:
          dist: loguniform
          min: 0.005
          max: 0.4
      - parameter_name: n_estimators
        space:
          dist: quniform
          min: 5
          max: 250
      - parameter_name: max_depth
        space:
          dist: quniform
          min: 1
          max: 120
      - parameter_name: colsample_bytree
        space:
          dist: uniform
          min: 0.6
          max: 1.0
      - parameter_name: lambda
        space:
          dist: loguniform
          min: 0.001
          max: 5.0
      - parameter_name: alpha
        space:
          dist: loguniform
          min: 0.001
          max: 5.0
      - parameter_name: max_leaves
        space:
          dist: quniform
          min: 5
          max: 120

  N_CANDIDATES: 5

  OPTIMIZATION_METRIC: f1_score
  # Classification: precision, recall, f1_score, roc_auc, accuracy (Accuracy not recommended)
  # Regression: mape
  VAL_SPLITS: 3

  MAX_EVALS: 100
  LOSS_THRESHOLD: null
  TIMEOUT_MINS: null
  MIN_PERFORMANCE: null

# FEATURE IMPORTANCE PARAMETERS
FEATURE_IMPORTANCE_PARAMS:
  IMPORTANCE_METHOD: shap

# LOGGER PARAMETERS
LOG_PARAMS:
  LEVEL: INFO # INFO
  TXT_FMT: null # default
  JSON_FMT: null # default
  FILTER_LVLS: null
  LOG_FILE: null # no log file will be written
  BACKUP_COUNT: null

# DEPLOYMENT PARAMETERS
DEPLOYMENT_PARAMS: null

# INFRASTRUCTURE PARAMETERS
INFRASTRUCTURE_PARAMS: null
