# # # # #
# GENERAL PARAMETERS
# # # # #

# PROJECT PARAMETERS
PROJECT_PARAMS:
  VERSION: v1.0.0
  PROJECT_NAME: ml-accelerator
  TARGET: diagnosis # target column
  # species (iris), wine_class (wine), diagnosis (breast_cancer), disease_progression (diabetes), MedHouseVal (california_housing)
  TASK: binary_classification 
  # regression, binary_classification, multiclass_classification, forecasting

# ENVIRONMENT PARAMETERS
ENV_PARAMS:
  ENV: dev
  REGION: sa-east-1
  BUCKET: breast-cancer-bucket-dev
  # project-name-bucket-env
  DATA_STORAGE_ENV: filesystem
  # filesystem, S3
  MODEL_STORAGE_ENV: filesystem
  # filesystem, S3, mlflow
  COMPUTE_ENV: local
  # local, sagemaker
  DOCKER_REPOSITORY: dockerhub
  # dockerhub, ecr

# # # # #
# DATA PROCESSING PARAMETERS
# # # # # 

# EXTRACT TRANSFORM LOAD PARAMETERS
ETL_PARAMS:
  ETL_SOURCE: sklearn
  # sklearn, filesystem, S3, postgresql

# STORAGE PARAMETERS
STORAGE_PARAMS:
  DATASET_NAME: breast_cancer
  # iris, wine, breast_cancer, diabetes, california_housing
  
  DATA_EXTENTION: parquet
  # csv, parquet
  PARTITION_COLUMNS: null

# DATA CLEANING PARAMETERS
DATA_CLEANING_PARAMS:
  OUTLIER_Z_THRESHOLD: 3.0 # 3.0

# FEATURE ENRICHER PARAMETERS
FEATURE_ENRICHER_PARAMS:
  ADD_OUTLIER_FEATURES: True
  OUTLIER_FEATURES_Z: 1.96
  FIBONACHI_FEATURES: null
  DERIVATIVE_FEATURES: null
  LAG_FEATURES: null
  ROLLING_FEATURES: null
  EMA_FEATURES: null
  TEMPORAL_EMBEDDING_FEATURES: null
  TEMPORAL_BASED_FEATURES: null
  HOLIDAY_FEATURES: null
  HOLIDAY_COUNTRY: US

# DATA TRANSFORMING PARAMETERS
DATA_TRANSFORMING_PARAMS:
  ENCODE_TARGET: True
  SCALE_NUM_FEATURES: True
  ENCODE_CAT_FEATURES: True

# FEATURE SELECTION PARAMETERS
FEATURE_SELECTION_PARAMS:
  FORCED_FEATURES: null
  TARGET_FEATURE_QUANTILE: 0.33
  FEATURE_FEATURE_QUANTILE: 0.95
  BORUTA_ALGORITHM: lightgbm
  # random_forest, lightgbm, xgboost
  RFE_N: 10
  K_BEST: 10
  TSFRESH_P_VALUE: 0.035
  TSFRESH_N: 5
  # RecurrentFeatureElimination
  MAX_FEATURES: 15

# # # # #
# MODELING PARAMETERS
# # # # #

# ML DATASETS PARAMETERS
ML_DATASETS_PARAMS:
  TEST_SIZE: 0.2

# CLASSIFICATION PARAMETERS
CLASSIFICATION_PARAMS:
  BALANCE_TRAIN: True
  BALANCE_METHOD: SMOTE
  # RandomOverSampler, RandomUnderSampler, SMOTE
  CLASS_WEIGHT: null
    # 1: 1
    # 0: 1
    # 2: 1
  CUTOFF: 0.5

# REGRESSION PARAMETERS
REGRESSION_PARAMS: null

# FORECASTING PARAMETERS
FORECASTING_PARAMS: null

# HYPER PARAMETER TUNING PARAMETERS
HYPER_PARAMETER_TUNING_PARAMS:
  ALGORITHMS:
    - random_forest
    - lightgbm
    - xgboost

  SEARCH_SPACE:
    - algorithm: random_forest
      hyper_parameters:
      - parameter_name: n_estimators
        space:
          dist: quniform
          min: 15
          max: 400
      - parameter_name: max_depth
        space:
          dist: quniform
          min: 15
          max: 200
      - parameter_name: min_samples_split
        space:
          dist: quniform
          min: 5
          max: 200
      - parameter_name: max_features
        space:
          dist: choice
          choices: 
          - 1.0
          - sqrt
    - algorithm: lightgbm
      hyper_parameters:
      # # ONLY FOR REGRESSION
      # - parameter_name: objective
      #   space:
      #     dist: choice
      #     choices:
      #     - regression 
      #     - regression_l1 
      #     - huber 
      #     - quantile 
      #     - mape
      - parameter_name: boosting_type
        space:
          dist: choice
          choices:
          - gbdt 
          - dart
      - parameter_name: n_estimators
        space:
          dist: quniform
          min: 5
          max: 300
      - parameter_name: max_depth
        space:
          dist: quniform
          min: 1
          max: 150
      - parameter_name: min_child_samples
        space:
          dist: quniform
          min: 5
          max: 100
      - parameter_name: learning_rate
        space:
          dist: loguniform
          min: 0.001
          max: 0.3
      - parameter_name: num_leaves
        space:
          dist: quniform
          min: 5
          max: 150
      - parameter_name: colsample_bytree
        space:
          dist: uniform
          min: 0.6
          max: 1.0
    - algorithm: xgboost
      hyper_parameters:
      # # ONLY FOR REGRESSION
      # - parameter_name: objective
      #   space:
      #     dist: choice
      #     choices:
      #     - reg:squarederror
      #     - reg:absoluteerror
      #     - reg:quantileerror
      - parameter_name: booster
        space:
          dist: choice
          choices:
          - gbtree
          - dart
      - parameter_name: eta
        space:
          dist: loguniform
          min: 0.005
          max: 0.4
      - parameter_name: n_estimators
        space:
          dist: quniform
          min: 5
          max: 250
      - parameter_name: max_depth
        space:
          dist: quniform
          min: 1
          max: 120
      - parameter_name: colsample_bytree
        space:
          dist: uniform
          min: 0.6
          max: 1.0
      - parameter_name: lambda
        space:
          dist: loguniform
          min: 0.001
          max: 5.0
      - parameter_name: alpha
        space:
          dist: loguniform
          min: 0.001
          max: 5.0
      - parameter_name: max_leaves
        space:
          dist: quniform
          min: 5
          max: 120

  N_CANDIDATES: 5

  OPTIMIZATION_METRIC: f1
  # Binary classification: precision, recall, f1, roc_auc, accuracy (Accuracy not recommended)
  # Multiclass classification: f1_weighted
  # Regression: mape
  VAL_SPLITS: 3

  MAX_EVALS: 20
  LOSS_THRESHOLD: 0.99
  TIMEOUT_MINS: 5
  MIN_PERFORMANCE: 0.95

# FEATURE IMPORTANCE PARAMETERS
FEATURE_IMPORTANCE_PARAMS:
  IMPORTANCE_METHOD: shap

# # # # #
# MLPIPELINE PARAMETERS
# # # # #
MLPIPELINE_PARAMS:
  TRANSFORMERS_STEPS:
    - DataCleaner
    - FeatureEnricher
    - DataStandardizer
    - FeatureSelector

# # # # #
# WORKFLOW PARAMETERS
# # # # #

MODEL_BUILDING_PARAMS:
  # Data Processing
  FIT_TRANSFORMERS: True
  SAVE_TRANSFORMERS: True
  PERSIST_DATASETS: False
  WRITE_MODE: overwrite
  # overwrite, append

  # Training
  TRAIN_PROD_PIPE: True
  TRAIN_STAGING_PIPES: True
  TRAIN_DEV_PIPES: False

  # Evaluating
  EVALUATE_PROD_PIPE: True
  EVALUATE_STAGING_PIPES: True
  EVALUATE_DEV_PIPES: True
  UPDATE_MODEL_STAGES: True
  UPDATE_PROD_MODEL: False

# # # # #
# OTHER PARAMETERS
# # # # #

# LOGGER PARAMETERS
LOG_PARAMS:
  LEVEL: DEBUG # DEBUG, INFO
  TXT_FMT: null # default
  JSON_FMT: null # default
  FILTER_LVLS: null
  LOG_FILE: null # no log file will be written
  BACKUP_COUNT: null

# DEPLOYMENT PARAMETERS
DEPLOYMENT_PARAMS:
  INFERENCE_HOST: 0.0.0.0
  INFERENCE_PORT: 8080

# INFRASTRUCTURE PARAMETERS
INFRASTRUCTURE_PARAMS: null
