# Use a base image compatible with arm64 architecture
# latest
FROM base-image:v1.0.0

# Expose port
EXPOSE 8501

# Run the app.py script when the container launches
CMD [ "streamlit", "run", "app.py" ]