services:

  # Data Processing Service
  data-processing:
    image: ${IMAGE_NAME}
    container_name: ${ENV}_data_processing_container_${VERSION}

    entrypoint:
      - python3
      - scripts/data_processing/data_processing.py

    command:
      - --fit_transformers
      - ${FIT_TRANSFORMERS}
      - --save_transformers
      - ${SAVE_TRANSFORMERS}
      - --persist_datasets
      - ${PERSIST_DATASETS}
      - --write_mode
      - ${WRITE_MODE}

    volumes:
      - ./../../${BUCKET_NAME}:/app/${BUCKET_NAME}
      # - ../${BUCKET_NAME}:/app/${BUCKET_NAME}

  # Tuning Service
  tuning:
    image: ${IMAGE_NAME}
    container_name: ${ENV}_tuning_container_${VERSION}

    entrypoint:
      - python3
      - scripts/tuning/tuning.py

    volumes:
      - ./../../${BUCKET_NAME}:/app/${BUCKET_NAME}

    depends_on:
      data-processing:
        condition: service_completed_successfully

  # Training Service
  training:
    image: ${IMAGE_NAME}
    container_name: ${ENV}_training_container_${VERSION}

    entrypoint:
      - python3
      - scripts/training/training.py

    command:
      - --train_prod_pipe
      - ${TRAIN_PROD_PIPE} 
      - --train_staging_pipes 
      - ${TRAIN_STAGING_PIPES} 
      - --train_dev_pipes
      - ${TRAIN_DEV_PIPES}

    volumes:
      - ./../../${BUCKET_NAME}:/app/${BUCKET_NAME}

    depends_on:
      tuning:
        condition: service_completed_successfully

  # Evaluating Service
  evaluating:
    image: ${IMAGE_NAME}
    container_name: ${ENV}_evaluating_container_${VERSION}

    entrypoint:
      - python3
      - scripts/evaluating/evaluating.py

    command:
      - --evaluate_prod_pipe 
      - ${EVALUATE_PROD_PIPE}
      - --evaluate_staging_pipes 
      - ${EVALUATE_STAGING_PIPES}
      - --evaluate_dev_pipes 
      - ${EVALUATE_DEV_PIPES}
      - --update_model_stages 
      - ${UPDATE_MODEL_STAGES}
      - --update_prod_model 
      - ${UPDATE_PROD_MODEL}

    volumes:
      - ./../../${BUCKET_NAME}:/app/${BUCKET_NAME}

    depends_on:
      training:
        condition: service_completed_successfully

  # Drift Service
  # drift:
  #   image: ${IMAGE_NAME}
  #   container_name: ${ENV}_drift_container_${VERSION}

  #   command:
  #     - python3
  #     - scripts/drift/drift.py
      
  #   volumes:
  #     - ./../../${BUCKET_NAME}:/app/${BUCKET_NAME}

  #   depends_on:
  #     evaluating:
  #       condition: service_completed_successfully

volumes:
  datasets:
    labels:
      environment: "development"
